name: Documentation
description: Report missing, incorrect or improved documentation.
title: "[DOC] "
labels: docs

body:
  - type: checkboxes
    attributes:
      label: Pandas version checks
      options:
        - label: >
            I have checked that the issue still exists on the latest versions of the docs
            on `main` [here](https://bioscience.readthedocs.io/en/latest/)
          required: true
  - type: textarea
    id: location
    attributes:
      label: Location of the documentation
      description: >
        Please provide the location of the documentation, e.g. "bioscience/release.rst" or the
        URL of the documentation, e.g.
        "https://bioscience.readthedocs.io/en/latest/release.html"
      placeholder: https://bioscience.readthedocs.io/en/latest/release.html
    validations:
      required: true
  - type: textarea
    id: suggested-new
    attributes:
      label: Suggested new feature for documentation
      description: >
        Please explain the new feature for documentation
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: Documentation problem
      description: >
        Please provide a description of what documentation you believe needs to be fixed/improved
    validations:
      required: false
  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested fix for documentation
      description: >
        Please explain the suggested fix and **why** it's better than the existing documentation
    validations:
      required: false

