name: Installation Issue
description: Report issues installing the bioScience library on your system
title: "[BLD] "
labels: [install, build]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Installation check
      options:
        - label: >
            I have read the [installation guide](https://bioscience.readthedocs.io/en/latest/install.html).
          required: true
  - type: input
    id: platform
    attributes:
      label: Platform
      description: >
        Please provide the output of ``import platform; print(platform.platform())``
    validations:
      required: true
  - type: dropdown
    id: method
    attributes:
      label: Installation Method
      description: >
        Please provide how you tried to install bioScience from a clean environment.
      options:
        - pip install
        - Built from source
        - Other
    validations:
      required: true
  - type: input
    id: bioscience
    attributes:
      label: bioScience Version
      description: >
        Please provide the version of bioScience you are trying to install.
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python Version
      description: >
        Please provide the installed version of Python.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Installation Logs
      description: >
        If possible, please copy and paste the installation logs when attempting to install bioScience.
      value: >
        Replace this line with the installation logs.


