name: Performance Issue
description: Report slow performance or memory issues when running bioScience
title: "[PER] "
labels: Performance

body:
  - type: checkboxes
    id: checks
    attributes:
      label: bioScience version checks
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
        - label: >
            I have confirmed this issue exists on the latest version of bioScience.
          required: true
        - label: >
            I have confirmed this issue exists on the main branch of bioScience.
  - type: textarea
    id: example
    attributes:
      label: Reproducible Example
      description: >
        Please provide a minimal, copy-pastable example that quantifies slow runtime or memory issues.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: bioScience version
      description: >
        Please paste the bioScience version
    validations:
      required: true
  - type: textarea
    id: prior-performance
    attributes:
      label: Prior Performance
      description: >
        If applicable, please provide the prior version of bioScience and output
        of the same reproducible example where the performance issue did not exist.

