# Correlation methods
DISTCORR = "Distance Correlation (distcorr)"
HOEFFDINGS = "Hoeffdings'D"
JACCARD = "Jaccard index"
KENDALL = "Kendall"
LOG_ODDS = "Log-odds ratio"
MANHATTAN = "Manhattan distance"
MCC = "Matthews Correlation Coefficient (MCC)"
MEDIAN = "Median"
MI = "Mutual Information (MI)"
NMI = "Normalized Mutual Information (NMI)"
PBC = "Point-biserial Correlation (PBC)"
PEARSON = "Pearson"
QUADRANT = "Quadrant (Q)"
SPEARMAN = "Spearman"
WEIGHTEDJACCARD = "Weighted Jaccard Index"