# Correlation methods
DISTCORR = "Distance Correlation (distcorr)"
HOEFFDINGS = "Hoeffdings'D"
KENDALL = "Kendall"
MCC = "Matthews Correlation Coefficient (MCC)"
MEDIAN = "Median"
MI = "Mutual Information (MI)"
NMI = "Normalized Mutual Information (NMI)"
PBC = "Point-biserial Correlation (PBC)"
PEARSON = "Pearson"
QUADRANT = "Quadrant (Q)"
SPEARMAN = "Spearman"