name: Build documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Documentation clean
      run: make -C docs/ clean

    - name: Documentation build
      run: make -C docs/ html
